import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { IconHome, IconMessage, IconUser } from '@tabler/icons-react';
import { FloatingNav } from '@/components/ui/floating-navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const navItems = [
  {
    name: 'Home',
    link: 'home',
    icon: <IconHome className="h-4 w-4 text-white" />,
  },
  {
    name: 'About',
    link: 'about',
    icon: <IconUser className="h-4 w-4 text-white" />,
  },
  {
    name: 'Features',
    link: 'features',
    icon: <IconMessage className="h-4 w-4 text-white" />,
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="home" className={cn('overflow-x-hidden', inter.className)}>
        <FloatingNav navItems={navItems} />
        {children}
      </body>
    </html>
  );
}
